### PR TITLE
onReady for resolveURL

### PR DESCRIPTION
**Pull request by sbauch**
I needed to know when a track was ready to be played so that I could programmatically start playing it, so I added this `onReady` prop.

Happy to write docs / examples, but wanted to run the approach by the maintainers first.

thanks for this component, super handy!

### CODE REVIEW

**Comment by voronianski** [comment]
@sbauch looks solid! Please add docs 👍

**Comment by sbauch** [comment]
@voronianski thanks! docs added.

**Comment by voronianski** [comment]
@sbauch merged. Pls check this issue - https://github.com/soundblogs/react-soundplayer/issues/58 if you have some info to share! :) thanks!

**Comment by sbauch** [comment]
I'd love to add us, but we're using this in a piece of private internal software at WeWork in the UX group.

**Comment by sbauch** [comment]
could we possibly release a new version of the package that has this work included?

**Pull request merged**
