### PR TITLE
Upgrade to postcss-cssnext from cssnext

### PR DESCRIPTION
**Pull request by joewestcott**
Fixes build by resolving error on node >6
```
react-soundplayer/node_modules/postcss/lib/lazy-result.js:200
            throw error;
            ^

TypeError: Path must be a string. Received undefined
```

### CODE REVIEW

**Comment by voronianski** [comment]
Have you tried the build? It doesn't work properly:

**Comment by joewestcott** [comment]
`postcss-cssnext` is the only way I'm able to build css, using `npm run build-css`

**Comment by joewestcott** [comment]
Oh are you attempting to build the `./examples`? This fixes the `react-soundplayer` main project, but I notice that `./examples` requires `cssnext` and fails now too. I didn't attempt to build `./examples` before submitting this PR as it's broken in other ways too. (#24 and #36) I'm working on fixing those now :)

**Comment by voronianski** [comment]
@joewestcott 

> postcss-cssnext is the only way I'm able to build css, using npm run build-css

I understand but `.cssnext` code should be changed somehow in order to get rid of `[object Object]`s.

> Oh are you attempting to build the ./examples?

Nope, I'm building the main project with `npm run build-css`

**Comment by joewestcott** [comment]
> I understand but .cssnext code should be changed somehow in order to get rid of [object Object]s.

So you'd prefer a solution that keeps `cssnext` over switching to `postcss-cssnext`? That's fine. My reasons for switching was it fixes the first error I mentioned above, and the package is depreciated.

**Comment by voronianski** [comment]
@joewestcott I think we need to fix the build inside `.cssnext` file and use `postcss-cssnext`. The output by current build is not valid. Check the content of built files:

```bash
dmitri@MacBook-Pro-Dmitri$ cat styles/buttons.css
[object Object]%
```

**Comment by joewestcott** [comment]
Try again now. The `cssnext` npm package has split & evolved to postcss, so we're using`postcss-cssnext` and `postcss-import`. Minification is no longer default, so I’ve not included it for the ./example builds. `basscss` updated to the latest version to prevent error on build.

**Comment by joewestcott** [comment]
Examples still doesn't look quite right, possibly because `highlight` or `basscss` isn't being properly loaded. Will investigate...

**Comment by voronianski** [comment]
@joewestcott Sorry, I won't update to basscss v8. I like v7 much more, it's simpler and ui is better. Also this update is not in scope of this PR.

**Comment by joewestcott** [comment]
Okay, so shall I close this one? Could you give me an idea of the changes made in this PR you're willing to accept? There is quite a few!

**Comment by voronianski** [comment]
@joewestcott let's stick to update to `postcss-cssnext` in this PR without updating basscss.

**Comment by joewestcott** [comment]
Happy to move CSS related deps to `./examples` too?

**Comment by voronianski** [comment]
@joewestcott what exactly?

**Comment by joewestcott** [comment]
`basscss` and `highlight.js` from `./package.json` to `./examples/package.json`

**Comment by voronianski** [comment]
@joewestcott doing this right now.

**Comment by voronianski** [comment]
@joewestcott https://github.com/soundblogs/react-soundplayer/commit/49bad48458144b05ad1bbf8f9f568e28e9a1453b it breaks examples bundle with React errors but that's a start.

**Comment by voronianski** [comment]
@joewestcott closing as necessary update to postcss is in master branch already.

**Pull request closed without merging**
